In [3]:
'''Consider the below code to answer further questions:'''
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [14]:
'''Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.
--------'''

While Python lists store a collection of ordered, alterable data objects, NumPy arrays only store a single type of object.

listtype = type(list_)
print('list_ Datatype : ',listtype)

print('Arraylist Datatype :', array_list.dtype)

list_ Datatype :  <class 'list'>
Arraylist Datatype : <U1


In [31]:
'''Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.
--------'''

for ele in list_:
    print(type(ele))
    
size = array_list.size

for i in range(0,size):
    print(type(array_list[i]))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [32]:
'''Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
--------'''

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

listtype = type(num_list)
print('list_ Datatype : ',listtype)

print('Arraylist Datatype :', num_array.dtype)

for ele in num_list:
    print(type(ele))
    
count = num_array.ndim
print(size)

for i in range(0,count):
    print(type(num_array[i]))


list_ Datatype :  <class 'list'>
Arraylist Datatype : int64
<class 'list'>
<class 'list'>
5
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [29]:
'''Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size'''

shape = num_array.shape
print('num_array shape :: ',shape)

size = num_array.size
print('num_array size :: ',size)

num_array shape ::  (2, 3)
num_array size ::  6


In [34]:
'''Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]
------'''

import numpy as np

npArr = np.zeros((3,3))
print(npArr)

print('Size :: ',npArr.size)
print('Shape :: ',npArr.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Size ::  9
Shape ::  (3, 3)


In [37]:
'''Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]'''

import numpy as np

npArr = np.eye(5,5)
print(npArr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
