In [66]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
arr = np.array(l)

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [8]:
arr1 = np.array([[1,2,3],[2,3,4]])

In [7]:
arr.ndim

1

In [9]:
arr1.ndim

2

In [10]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [12]:
mat = np.matrix(l)

In [15]:
## will convert anything to array if any array is not present
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [14]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
a = arr

In [18]:
a

array([1, 2, 3, 4, 5])

In [29]:
## shallow copy operation
arr[0] = 100

In [20]:
arr

array([100,   2,   3,   4,   5])

In [21]:
a

array([100,   2,   3,   4,   5])

In [30]:
## deep copy
b = np.copy(arr)

In [24]:
b

array([100,   2,   3,   4,   5])

In [25]:
b[0] = 234

In [27]:
b

array([234,   2,   3,   4,   5])

In [28]:
arr

array([100,   2,   3,   4,   5])

In [31]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [32]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [34]:
list((i*i for i in range(5)))

[0, 1, 4, 9, 16]

In [35]:
iterable = (i*i for i in range(5))

In [36]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [37]:
np.fromstring('23 45 56', sep = ' ')

array([23., 45., 56.])

In [39]:
np.fromstring('23,45,56', sep = ',')

array([23., 45., 56.])

In [40]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [41]:
arr.ndim

1

In [43]:
arr1.ndim

2

In [44]:
arr.size

5

In [45]:
arr1.size

6

In [46]:
arr.shape

(5,)

In [47]:
arr1.shape

(2, 3)

In [48]:
arr.dtype

dtype('int64')

In [49]:
arr1.dtype

dtype('int64')

In [52]:
list(range(5))

[0, 1, 2, 3, 4]

In [53]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [54]:
list(range(0.4,10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [55]:
np.arange(.4, 10.4, 0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [56]:
list(np.arange(.4, 10.4, 0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [57]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [58]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [59]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [62]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [63]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [66]:
arr = np.ones((3,4))

In [67]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [69]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [70]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [73]:
arr1 = np.eye(5)

In [74]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
import pandas as pd

In [76]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [77]:
np.random.rand(2,3)

array([[0.69510646, 0.83026033, 0.55201477],
       [0.16647593, 0.41999055, 0.83108005]])

In [78]:
np.random.randn(2,3)

array([[-0.00934586, -2.01497816, -1.17182863],
       [ 0.47887373,  0.94938745, -2.12328362]])

In [ ]:
## rand.. mean and std can be anything
## randn.. mean will be 0 and std will be 1

In [80]:
arr2 = np.random.randint(1,5,(3,4))

In [81]:
arr2

array([[2, 2, 2, 1],
       [2, 2, 4, 4],
       [1, 3, 2, 3]])

In [82]:
arr2.size

12

In [83]:
arr2.shape

(3, 4)

In [84]:
arr2.reshape(6,2)

array([[2, 2],
       [2, 1],
       [2, 2],
       [4, 4],
       [1, 3],
       [2, 3]])

In [85]:
arr2.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [86]:
arr2.reshape(4,3)

array([[2, 2, 2],
       [1, 2, 2],
       [4, 4, 1],
       [3, 2, 3]])

In [87]:
arr2.reshape(4,-1)

array([[2, 2, 2],
       [1, 2, 2],
       [4, 4, 1],
       [3, 2, 3]])

In [88]:
arr2.reshape(2,2,3)

array([[[2, 2, 2],
        [1, 2, 2]],

       [[4, 4, 1],
        [3, 2, 3]]])

In [89]:
arr1 = np.random.randint(1,10,(5,6))

In [90]:
arr1

array([[3, 2, 7, 5, 9, 6],
       [1, 9, 2, 3, 8, 2],
       [7, 4, 4, 6, 9, 6],
       [4, 5, 8, 7, 7, 9],
       [7, 1, 8, 4, 6, 9]])

In [91]:
arr1>8

array([[False, False, False, False,  True, False],
       [False,  True, False, False, False, False],
       [False, False, False, False,  True, False],
       [False, False, False, False, False,  True],
       [False, False, False, False, False,  True]])

In [92]:
arr1[arr1>8]

array([9, 9, 9, 9, 9])

In [93]:
arr1

array([[3, 2, 7, 5, 9, 6],
       [1, 9, 2, 3, 8, 2],
       [7, 4, 4, 6, 9, 6],
       [4, 5, 8, 7, 7, 9],
       [7, 1, 8, 4, 6, 9]])

In [96]:
arr1[0,[0,1]]

array([3, 2])

In [97]:
arr1[2:4,[2,3]]

array([[4, 6],
       [8, 7]])

In [98]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [99]:
arr1

array([[1, 1, 2],
       [2, 1, 2],
       [1, 2, 2]])

In [100]:
arr2

array([[2, 1, 2],
       [1, 1, 2],
       [2, 2, 1]])

In [101]:
arr1+arr2

array([[3, 2, 4],
       [3, 2, 4],
       [3, 4, 3]])

In [102]:
arr1-arr2

array([[-1,  0,  0],
       [ 1,  0,  0],
       [-1,  0,  1]])

In [103]:
arr1*arr2

array([[2, 1, 4],
       [2, 1, 4],
       [2, 4, 2]])

In [105]:
## * will give index wise multiplication
## @ will give matrix multiplication
arr1@arr2

array([[7, 6, 6],
       [9, 7, 8],
       [8, 7, 8]])

In [106]:
arr1/arr2

array([[0.5, 1. , 1. ],
       [2. , 1. , 1. ],
       [0.5, 1. , 2. ]])

In [107]:
arr1/0

/tmp/ipykernel_4369/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
## Numpy Broadcasting

In [2]:
arr = np.zeros((3,4))

In [3]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [5]:
a = np.array([1,2,3,4])

In [6]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [7]:
b = np.array([[3,4,5]])

In [8]:
arr+b

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [9]:
b.T

array([[3],
       [4],
       [5]])

In [10]:
arr1 = arr+b.T

In [11]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [12]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [13]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [14]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [15]:
np.min(arr1)

3.0

In [16]:
np.max(arr1)

5.0

In [20]:
arr = np.random.randint(1,10 , (4,4))
arr

array([[3, 1, 1, 4],
       [2, 8, 3, 3],
       [4, 1, 4, 7],
       [9, 6, 9, 5]])

In [21]:
arr.reshape(2,8)

array([[3, 1, 1, 4, 2, 8, 3, 3],
       [4, 1, 4, 7, 9, 6, 9, 5]])

In [22]:
arr.T

array([[3, 2, 4, 9],
       [1, 8, 1, 6],
       [1, 3, 4, 9],
       [4, 3, 7, 5]])

In [23]:
arr.flatten()

array([3, 1, 1, 4, 2, 8, 3, 3, 4, 1, 4, 7, 9, 6, 9, 5])

In [24]:
arr

array([[3, 1, 1, 4],
       [2, 8, 3, 3],
       [4, 1, 4, 7],
       [9, 6, 9, 5]])

In [28]:
## axis is mandatory parameter here
## expand dimention will always try to get upper dimention array
np.expand_dims(arr, axis=1)

array([[[3, 1, 1, 4]],

       [[2, 8, 3, 3]],

       [[4, 1, 4, 7]],

       [[9, 6, 9, 5]]])

In [29]:
np.expand_dims(arr, axis=0)

array([[[3, 1, 1, 4],
        [2, 8, 3, 3],
        [4, 1, 4, 7],
        [9, 6, 9, 5]]])

In [30]:
data = np.array([[1], [2], [3]])

In [31]:
np.squeeze(data)

array([1, 2, 3])

In [ ]:
## squeeze will give lesser dimention array

In [32]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [33]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [34]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
## Numpy : Binary operations

In [69]:
arr1 = np.random.randint(1,10, (3,4))
arr2 = np.random.randint(1,10, (3,4))

In [37]:
arr1

array([[5, 8, 6, 2],
       [7, 1, 2, 9],
       [1, 6, 7, 7]])

In [38]:
arr2

array([[7, 6, 8, 3],
       [7, 8, 7, 7],
       [9, 5, 7, 4]])

In [39]:
arr1+arr2

array([[12, 14, 14,  5],
       [14,  9,  9, 16],
       [10, 11, 14, 11]])

In [40]:
arr1-arr2

array([[-2,  2, -2, -1],
       [ 0, -7, -5,  2],
       [-8,  1,  0,  3]])

In [41]:
arr1*arr2

array([[35, 48, 48,  6],
       [49,  8, 14, 63],
       [ 9, 30, 49, 28]])

In [42]:
arr1/arr2

array([[0.71428571, 1.33333333, 0.75      , 0.66666667],
       [1.        , 0.125     , 0.28571429, 1.28571429],
       [0.11111111, 1.2       , 1.        , 1.75      ]])

In [43]:
arr1**arr2

array([[  78125,  262144, 1679616,       8],
       [ 823543,       1,     128, 4782969],
       [      1,    7776,  823543,    2401]])

In [44]:
~arr1

array([[ -6,  -9,  -7,  -3],
       [ -8,  -2,  -3, -10],
       [ -2,  -7,  -8,  -8]])

In [45]:
arr1>arr2

array([[False,  True, False, False],
       [False, False, False,  True],
       [False,  True, False,  True]])

In [ ]:
## Numpy : String operation

In [67]:
arr = np.array(['puja', 'malviya'])

In [68]:
arr

array(['puja', 'malviya'], dtype='<U7')

In [48]:
np.char.upper(arr)

array(['PUJA', 'MALVIYA'], dtype='<U7')

In [49]:
np.char.capitalize(arr)

array(['Puja', 'Malviya'], dtype='<U7')

In [50]:
np.char.title(arr)

array(['Puja', 'Malviya'], dtype='<U7')

In [ ]:
## Numpy : Mathematical Operations

In [70]:
arr1

array([[9, 4, 9, 7],
       [1, 4, 4, 9],
       [2, 8, 9, 4]])

In [71]:
np.sin(arr1)

array([[ 0.41211849, -0.7568025 ,  0.41211849,  0.6569866 ],
       [ 0.84147098, -0.7568025 , -0.7568025 ,  0.41211849],
       [ 0.90929743,  0.98935825,  0.41211849, -0.7568025 ]])

In [53]:
np.cos(arr1)

array([[ 0.28366219, -0.14550003,  0.96017029, -0.41614684],
       [ 0.75390225,  0.54030231, -0.41614684, -0.91113026],
       [ 0.54030231,  0.96017029,  0.75390225,  0.75390225]])

In [54]:
np.tan(arr1)

array([[-3.38051501, -6.79971146, -0.29100619, -2.18503986],
       [ 0.87144798,  1.55740772, -2.18503986, -0.45231566],
       [ 1.55740772, -0.29100619,  0.87144798,  0.87144798]])

In [55]:
np.log10(arr1)

array([[0.69897   , 0.90308999, 0.77815125, 0.30103   ],
       [0.84509804, 0.        , 0.30103   , 0.95424251],
       [0.        , 0.77815125, 0.84509804, 0.84509804]])

In [56]:
np.exp(arr1)

array([[1.48413159e+02, 2.98095799e+03, 4.03428793e+02, 7.38905610e+00],
       [1.09663316e+03, 2.71828183e+00, 7.38905610e+00, 8.10308393e+03],
       [2.71828183e+00, 4.03428793e+02, 1.09663316e+03, 1.09663316e+03]])

In [61]:
np.power(arr1,2)

array([[25, 64, 36,  4],
       [49,  1,  4, 81],
       [ 1, 36, 49, 49]])

In [72]:
np.mean(arr1)

5.833333333333333

In [73]:
np.median(arr1)

5.5

In [74]:
np.std(arr1)

2.852873794770615

In [75]:
np.var(arr1)

8.13888888888889

In [76]:
np.min(arr1)

1

In [77]:
np.max(arr1)

9

In [ ]:
## Numpy Arithmetic Operations

In [78]:
arr1

array([[9, 4, 9, 7],
       [1, 4, 4, 9],
       [2, 8, 9, 4]])

In [79]:
arr2

array([[2, 8, 7, 9],
       [3, 3, 6, 6],
       [4, 8, 9, 4]])

In [80]:
arr1-arr2

array([[ 7, -4,  2, -2],
       [-2,  1, -2,  3],
       [-2,  0,  0,  0]])

In [81]:
np.subtract(arr1,arr2)

array([[ 7, -4,  2, -2],
       [-2,  1, -2,  3],
       [-2,  0,  0,  0]])

In [82]:
np.multiply(arr1, arr2)

array([[18, 32, 63, 63],
       [ 3, 12, 24, 54],
       [ 8, 64, 81, 16]])

In [83]:
np.mod(arr1,arr2)

array([[1, 4, 2, 7],
       [1, 1, 4, 3],
       [2, 0, 0, 0]])

In [84]:
np.power(arr1,arr2)

array([[       81,     65536,   4782969,  40353607],
       [        1,        64,      4096,    531441],
       [       16,  16777216, 387420489,       256]])

In [85]:
np.sqrt(arr1)

array([[3.        , 2.        , 3.        , 2.64575131],
       [1.        , 2.        , 2.        , 3.        ],
       [1.41421356, 2.82842712, 3.        , 2.        ]])

In [ ]:
## Numpy : Statistical Functions

In [87]:
np.mean(arr1)

5.833333333333333

In [89]:
np.std(arr1)

2.852873794770615

In [90]:
np.median(arr1)

5.5

In [ ]:
## Sort, Search & Counting Functions

In [91]:
import numpy as np

In [98]:
arr = np.array([4,2,8,5,3,9,12,56])

In [99]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [100]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [102]:
## this will give the index 
## if new data we are passing then it will give index where the new elemnet should be placed
np.searchsorted(arr,6)

5

In [107]:
arr1 = np.array([0,324,65,6,6,0,0,0,234,90])

In [108]:
arr1

array([  0, 324,  65,   6,   6,   0,   0,   0, 234,  90])

In [109]:
np.count_nonzero(arr1)

6

In [110]:
np.where(arr1>0)

(array([1, 2, 3, 4, 8, 9]),)

In [114]:
np.extract(arr1>2,arr1)

array([324,  65,   6,   6, 234,  90])

In [ ]:
## Numpy : Byte Swapping

In [115]:
arr1

array([  0, 324,  65,   6,   6,   0,   0,   0, 234,  90])

In [116]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [119]:
## it will swap the original data with byte
## if will pass True inside function then it is permanent change
arr.byteswap()

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [ ]:
## Numpy : Copies & Views

In [122]:
arr1

array([  0, 324,  65,   6,   6,   0,   0,   0, 234,  90])

In [121]:
a = np.copy(arr1)

In [123]:
a

array([  0, 324,  65,   6,   6,   0,   0,   0, 234,  90])

In [124]:
b = arr1.view()

In [125]:
b

array([  0, 324,  65,   6,   6,   0,   0,   0, 234,  90])

In [126]:
b[0] = 234

In [127]:
b

array([234, 324,  65,   6,   6,   0,   0,   0, 234,  90])

In [128]:
arr1

array([234, 324,  65,   6,   6,   0,   0,   0, 234,  90])

In [ ]:
## view is making shallow copy

In [ ]:
## Numpy : Matrix Library

In [129]:
import numpy.matlib as nm

In [130]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [132]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [133]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
## Numpy : Linear Algebra

In [135]:
arr1 = np.random.randint([[2,3],[4,5]])

In [136]:
arr2 = np.random.randint([[5,3],[2,5]])

In [137]:
arr1

array([[0, 2],
       [2, 3]])

In [138]:
arr2

array([[3, 0],
       [1, 0]])

In [139]:
## dot product
np.dot(arr1, arr2)

array([[2, 0],
       [9, 0]])

In [140]:
arr1@arr2

array([[2, 0],
       [9, 0]])